version: '3'

services:
  backend:
    build:
      context: ./lstm-stock-predictor-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./lstm-stock-predictor-frontend
    ports:
      - "3000:3000"
